version: '3.9'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_python
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODELS_PATH=/models
    volumes:
      - ollama_models:/models

  python_ai_proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_ai_proxy
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - ollama

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui_python
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://python_ai_proxy:8000
      - OLLAMA_BASE_URL=http://python_ai_proxy:8000
    depends_on:
      - python_ai_proxy
    volumes:
      - openwebui_data:/app/backend/data

volumes:
  ollama_models:
  openwebui_data: